### ISSUE TITLE
Table width exceeds wanted width of 100 characters.

### ISSUE THREAD

**Issue by theodotos** [riboseinc/digicert-cli#58] opened 2018-08-22 06:06 UTC
Hello,

I am running `digicert order list` and getting the following error:

```
$ digicert order list
Traceback (most recent call last):
        22: from /home/theodotos/bin/digicert:21:in `<main>'
        21: from /home/theodotos/arena/digicert-cli/lib/digicert/cli.rb:35:in `start'
        20: from /usr/lib/ruby/vendor_ruby/thor/base.rb:444:in `start'
        19: from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
        18: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
        17: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
        16: from /usr/lib/ruby/vendor_ruby/thor.rb:242:in `block in subcommand'
        15: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:115:in `invoke'
        14: from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
        13: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
        12: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
        11: from /home/theodotos/arena/digicert-cli/lib/digicert/cli/commands/order.rb:12:in `list'
        10: from /usr/lib/ruby/vendor_ruby/thor/shell.rb:59:in `say'
         9: from /usr/lib/ruby/vendor_ruby/thor/shell/basic.rb:91:in `say'
         8: from /var/lib/gems/2.5.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `render'
         7: from /var/lib/gems/2.5.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `map'
         6: from /var/lib/gems/2.5.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `block in render'
         5: from /var/lib/gems/2.5.0/gems/terminal-table-1.8.0/lib/terminal-table/separator.rb:6:in `render'
         4: from /var/lib/gems/2.5.0/gems/terminal-table-1.8.0/lib/terminal-table/separator.rb:6:in `map'
         3: from /var/lib/gems/2.5.0/gems/terminal-table-1.8.0/lib/terminal-table/separator.rb:7:in `block in render'
         2: from /var/lib/gems/2.5.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:97:in `column_width'
         1: from /var/lib/gems/2.5.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:339:in `column_widths'
/var/lib/gems/2.5.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:305:in `recalc_column_widths': Table width exceeds wanted width of 100 characters. (RuntimeError)
```

My ruby version:

```
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

**Comment by ronaldtse** [comment] 2018-08-22 06:58
@theodotos thanks for reporting this issue! Let's see if @abunashir has time to check on this.

**Comment by abunashir** [comment] 2018-08-22 12:10
I will look into this and possibly add a solution soon, thanks :)

**Comment by abunashir** [comment] 2018-08-23 14:58
Hi @theodotos thanks for reporting the issue again, it was a bug. I just pushed a new version and it should fix the issue, but please check it out and let us know if that fixes the issue, thanks!

New Release: https://rubygems.org/gems/digicert-cli/versions/0.4.2

cc: @ronaldtse

**Comment by ronaldtse** [comment] 2018-08-24 05:11
Thanks @abunashir !

**Comment by abunashir** [comment] 2018-10-24 08:18
Closing it now, but please feel free to re-open it if the issue is still there.

**Closed by abunashir** 2018-10-24 08:18 UTC
Labels: bug
